import type { VesselRow } from '@/types/vessel'

const NOW = new Date().toISOString()

export const DEMO_VESSELS: VesselRow[] = [
  // ── NORMAL CARGO (12) ───────────────────────────────────────────────────────

  {
    mmsi: '215432100',
    imo_number: 'IMO9456789',
    vessel_name: 'MSC ISABELLA',
    call_sign: 'LNAB4',
    flag_state: 'Malta',
    ship_type: 70,
    type_category: 'Cargo',
    type_color: '#3498DB',
    lat: 36.8,
    lon: -13.4,
    sog: 14.2,
    cog: 278.0,
    true_heading: 277,
    nav_status: 0,
    destination: 'CHARLESTON',
    is_active: true,
    is_anomaly: false,
    sanctions_match: false,
    dark_fleet_score: null,
    last_update: NOW,
  },
  {
    mmsi: '477293800',
    imo_number: 'IMO9678234',
    vessel_name: 'EVER GLORY',
    call_sign: 'VROA3',
    flag_state: 'Hong Kong',
    ship_type: 71,
    type_category: 'Cargo',
    type_color: '#3498DB',
    lat: 22.1,
    lon: -60.8,
    sog: 16.8,
    cog: 304.0,
    true_heading: 303,
    nav_status: 0,
    destination: 'ROTTERDAM',
    is_active: true,
    is_anomaly: false,
    sanctions_match: false,
    dark_fleet_score: null,
    last_update: NOW,
  },
  {
    mmsi: '477812300',
    imo_number: 'IMO9731204',
    vessel_name: 'COSCO SHIPPING STAR',
    call_sign: 'VRPT2',
    flag_state: 'Hong Kong',
    ship_type: 70,
    type_category: 'Cargo',
    type_color: '#3498DB',
    lat: 1.2,
    lon: -24.6,
    sog: 15.1,
    cog: 328.0,
    true_heading: 327,
    nav_status: 0,
    destination: 'FELIXSTOWE',
    is_active: true,
    is_anomaly: false,
    sanctions_match: false,
    dark_fleet_score: null,
    last_update: NOW,
  },
  {
    mmsi: '440231000',
    imo_number: 'IMO9412876',
    vessel_name: 'HYUNDAI SUPREME',
    call_sign: 'DTMK5',
    flag_state: 'South Korea',
    ship_type: 70,
    type_category: 'Cargo',
    type_color: '#3498DB',
    lat: 28.4,
    lon: 172.6,
    sog: 13.9,
    cog: 82.0,
    true_heading: 81,
    nav_status: 0,
    destination: 'LONG BEACH',
    is_active: true,
    is_anomaly: false,
    sanctions_match: false,
    dark_fleet_score: null,
    last_update: NOW,
  },
  {
    mmsi: '477604200',
    imo_number: 'IMO9803451',
    vessel_name: 'ONE INNOVATION',
    call_sign: 'VRBB9',
    flag_state: 'Hong Kong',
    ship_type: 71,
    type_category: 'Cargo',
    type_color: '#3498DB',
    lat: 34.7,
    lon: -145.2,
    sog: 17.3,
    cog: 95.0,
    true_heading: 94,
    nav_status: 0,
    destination: 'YOKOHAMA',
    is_active: true,
    is_anomaly: false,
    sanctions_match: false,
    dark_fleet_score: null,
    last_update: NOW,
  },
  {
    mmsi: '564871200',
    imo_number: 'IMO9601238',
    vessel_name: 'YANG MING WITNESS',
    call_sign: 'S6PQ8',
    flag_state: 'Singapore',
    ship_type: 70,
    type_category: 'Cargo',
    type_color: '#3498DB',
    lat: 18.6,
    lon: -158.4,
    sog: 15.7,
    cog: 258.0,
    true_heading: 257,
    nav_status: 0,
    destination: 'KAOHSIUNG',
    is_active: true,
    is_anomaly: false,
    sanctions_match: false,
    dark_fleet_score: null,
    last_update: NOW,
  },
  {
    mmsi: '219847000',
    imo_number: 'IMO9543210',
    vessel_name: 'MAERSK EDMONTON',
    call_sign: 'OZBY6',
    flag_state: 'Denmark',
    ship_type: 70,
    type_category: 'Cargo',
    type_color: '#3498DB',
    lat: -15.3,
    lon: 67.8,
    sog: 14.8,
    cog: 218.0,
    true_heading: 217,
    nav_status: 0,
    destination: 'PORT LOUIS',
    is_active: true,
    is_anomaly: false,
    sanctions_match: false,
    dark_fleet_score: null,
    last_update: NOW,
  },
  {
    mmsi: '228312000',
    imo_number: 'IMO9712345',
    vessel_name: 'CMA CGM TITAN',
    call_sign: 'FMYA3',
    flag_state: 'France',
    ship_type: 71,
    type_category: 'Cargo',
    type_color: '#3498DB',
    lat: 6.4,
    lon: 72.9,
    sog: 16.2,
    cog: 142.0,
    true_heading: 141,
    nav_status: 0,
    destination: 'COLOMBO',
    is_active: true,
    is_anomaly: false,
    sanctions_match: false,
    dark_fleet_score: null,
    last_update: NOW,
  },
  {
    mmsi: '564321900',
    imo_number: 'IMO9634521',
    vessel_name: 'PIL DARWIN',
    call_sign: 'S6XJ2',
    flag_state: 'Singapore',
    ship_type: 70,
    type_category: 'Cargo',
    type_color: '#3498DB',
    lat: -10.8,
    lon: 104.3,
    sog: 13.4,
    cog: 176.0,
    true_heading: 175,
    nav_status: 0,
    destination: 'FREMANTLE',
    is_active: true,
    is_anomaly: false,
    sanctions_match: false,
    dark_fleet_score: null,
    last_update: NOW,
  },
  {
    mmsi: '352431700',
    imo_number: 'IMO9567890',
    vessel_name: 'ATLANTIC PHOENIX',
    call_sign: '3EKL7',
    flag_state: 'Panama',
    ship_type: 70,
    type_category: 'Cargo',
    type_color: '#3498DB',
    lat: 14.6,
    lon: -38.2,
    sog: 12.9,
    cog: 187.0,
    true_heading: 186,
    nav_status: 0,
    destination: 'SANTOS',
    is_active: true,
    is_anomaly: false,
    sanctions_match: false,
    dark_fleet_score: null,
    last_update: NOW,
  },
  {
    mmsi: '215781200',
    imo_number: 'IMO9489067',
    vessel_name: 'MEDITERRANEAN BRIDGE',
    call_sign: 'LNGQ5',
    flag_state: 'Malta',
    ship_type: 70,
    type_category: 'Cargo',
    type_color: '#3498DB',
    lat: 33.8,
    lon: 22.4,
    sog: 14.1,
    cog: 91.0,
    true_heading: 90,
    nav_status: 0,
    destination: 'PORT SAID',
    is_active: true,
    is_anomaly: false,
    sanctions_match: false,
    dark_fleet_score: null,
    last_update: NOW,
  },
  {
    mmsi: '352876500',
    imo_number: 'IMO9512034',
    vessel_name: 'PACIFIC MERIDIAN',
    call_sign: '3FRW4',
    flag_state: 'Panama',
    ship_type: 71,
    type_category: 'Cargo',
    type_color: '#3498DB',
    lat: -31.4,
    lon: -148.7,
    sog: 15.3,
    cog: 44.0,
    true_heading: 43,
    nav_status: 0,
    destination: 'AUCKLAND',
    is_active: true,
    is_anomaly: false,
    sanctions_match: false,
    dark_fleet_score: null,
    last_update: NOW,
  },

  // ── NORMAL TANKERS (4) ──────────────────────────────────────────────────────

  {
    mmsi: '248671300',
    imo_number: 'IMO9678901',
    vessel_name: 'FRONT ALTO',
    call_sign: '9HA45',
    flag_state: 'Malta',
    ship_type: 80,
    type_category: 'Tanker',
    type_color: '#E74C3C',
    lat: 24.8,
    lon: 57.4,
    sog: 13.6,
    cog: 232.0,
    true_heading: 231,
    nav_status: 0,
    destination: 'FUJAIRAH',
    is_active: true,
    is_anomaly: false,
    sanctions_match: false,
    dark_fleet_score: null,
    last_update: NOW,
  },
  {
    mmsi: '219543100',
    imo_number: 'IMO9723456',
    vessel_name: 'NORDIC HAWK',
    call_sign: 'OZAN3',
    flag_state: 'Denmark',
    ship_type: 80,
    type_category: 'Tanker',
    type_color: '#E74C3C',
    lat: 1.8,
    lon: 102.4,
    sog: 11.2,
    cog: 138.0,
    true_heading: 137,
    nav_status: 0,
    destination: 'SINGAPORE',
    is_active: true,
    is_anomaly: false,
    sanctions_match: false,
    dark_fleet_score: null,
    last_update: NOW,
  },
  {
    mmsi: '477341200',
    imo_number: 'IMO9634890',
    vessel_name: 'GULF MERCURY',
    call_sign: 'VRPX6',
    flag_state: 'Hong Kong',
    ship_type: 81,
    type_category: 'Tanker',
    type_color: '#E74C3C',
    lat: 26.1,
    lon: 54.8,
    sog: 12.7,
    cog: 315.0,
    true_heading: 314,
    nav_status: 0,
    destination: 'ROTTERDAM',
    is_active: true,
    is_anomaly: false,
    sanctions_match: false,
    dark_fleet_score: null,
    last_update: NOW,
  },
  {
    mmsi: '566234100',
    imo_number: 'IMO9801234',
    vessel_name: 'STRAITS VOYAGER',
    call_sign: 'S6MN1',
    flag_state: 'Singapore',
    ship_type: 80,
    type_category: 'Tanker',
    type_color: '#E74C3C',
    lat: 4.2,
    lon: 100.6,
    sog: 10.8,
    cog: 152.0,
    true_heading: 151,
    nav_status: 0,
    destination: 'PORT DICKSON',
    is_active: true,
    is_anomaly: false,
    sanctions_match: false,
    dark_fleet_score: null,
    last_update: NOW,
  },

  // ── PASSENGER VESSELS (3) ───────────────────────────────────────────────────

  {
    mmsi: '247234500',
    imo_number: 'IMO9512678',
    vessel_name: 'COSTA MEDITERRANEA',
    call_sign: 'IBQR2',
    flag_state: 'Italy',
    ship_type: 69,
    type_category: 'Passenger',
    type_color: '#9B59B6',
    lat: 38.2,
    lon: 14.6,
    sog: 18.4,
    cog: 174.0,
    true_heading: 173,
    nav_status: 0,
    destination: 'CIVITAVECCHIA',
    is_active: true,
    is_anomaly: false,
    sanctions_match: false,
    dark_fleet_score: null,
    last_update: NOW,
  },
  {
    mmsi: '338712400',
    imo_number: 'IMO9434276',
    vessel_name: 'CARNIVAL SUNRISE',
    call_sign: 'WDH4728',
    flag_state: 'United States',
    ship_type: 69,
    type_category: 'Passenger',
    type_color: '#9B59B6',
    lat: 18.4,
    lon: -66.2,
    sog: 19.1,
    cog: 267.0,
    true_heading: 266,
    nav_status: 0,
    destination: 'MIAMI',
    is_active: true,
    is_anomaly: false,
    sanctions_match: false,
    dark_fleet_score: null,
    last_update: NOW,
  },
  {
    mmsi: '311012300',
    imo_number: 'IMO9751234',
    vessel_name: 'CELEBRITY EDGE',
    call_sign: 'C6PQ3',
    flag_state: 'Bahamas',
    ship_type: 69,
    type_category: 'Passenger',
    type_color: '#9B59B6',
    lat: 25.8,
    lon: -77.4,
    sog: 20.2,
    cog: 351.0,
    true_heading: 350,
    nav_status: 0,
    destination: 'PORT CANAVERAL',
    is_active: true,
    is_anomaly: false,
    sanctions_match: false,
    dark_fleet_score: null,
    last_update: NOW,
  },

  // ── FISHING VESSEL (1 normal) ───────────────────────────────────────────────

  {
    mmsi: '503421700',
    imo_number: null,
    vessel_name: 'SOUTHERN CROSS 3',
    call_sign: 'VJK23',
    flag_state: 'Australia',
    ship_type: 30,
    type_category: 'Fishing',
    type_color: '#27AE60',
    lat: -42.6,
    lon: 148.3,
    sog: 4.2,
    cog: 87.0,
    true_heading: 86,
    nav_status: 7,
    destination: null,
    is_active: true,
    is_anomaly: false,
    sanctions_match: false,
    dark_fleet_score: null,
    last_update: NOW,
  },

  // ── HIGH SPEED CRAFT (2) ────────────────────────────────────────────────────

  {
    mmsi: '232451800',
    imo_number: 'IMO9234567',
    vessel_name: 'SOLENT EXPRESS',
    call_sign: '2HRX5',
    flag_state: 'United Kingdom',
    ship_type: 40,
    type_category: 'High Speed',
    type_color: '#F39C12',
    lat: 50.6,
    lon: -1.2,
    sog: 32.4,
    cog: 188.0,
    true_heading: 187,
    nav_status: 0,
    destination: 'CHERBOURG',
    is_active: true,
    is_anomaly: false,
    sanctions_match: false,
    dark_fleet_score: null,
    last_update: NOW,
  },
  {
    mmsi: '563712800',
    imo_number: 'IMO9312456',
    vessel_name: 'MARINA BAY FLYER',
    call_sign: 'S6TR9',
    flag_state: 'Singapore',
    ship_type: 40,
    type_category: 'High Speed',
    type_color: '#F39C12',
    lat: 1.1,
    lon: 103.8,
    sog: 28.7,
    cog: 82.0,
    true_heading: 81,
    nav_status: 0,
    destination: 'BATAM',
    is_active: true,
    is_anomaly: false,
    sanctions_match: false,
    dark_fleet_score: null,
    last_update: NOW,
  },

  // ── FLAGGED VESSELS (6) ─────────────────────────────────────────────────────

  // 1. Sanctions match — cargo near Strait of Hormuz
  {
    mmsi: '352193400',
    imo_number: 'IMO9344521',
    vessel_name: 'SILVER PIONEER',
    call_sign: '3EJD9',
    flag_state: 'Panama',
    ship_type: 70,
    type_category: 'Cargo',
    type_color: '#EF4444',
    lat: 26.5,
    lon: 56.3,
    sog: 0.2,
    cog: 12.0,
    true_heading: 11,
    nav_status: 1,
    destination: 'BANDAR ABBAS',
    is_active: true,
    is_anomaly: false,
    sanctions_match: true,
    dark_fleet_score: 54,
    last_update: NOW,
  },

  // 2. Anomaly + dark fleet — tanker loitering near Singapore
  {
    mmsi: '457881200',
    imo_number: 'IMO9401278',
    vessel_name: 'PACIFIC GHOST',
    call_sign: 'TJGM4',
    flag_state: 'Cameroon',
    ship_type: 80,
    type_category: 'Tanker',
    type_color: '#F97316',
    lat: 3.2,
    lon: 104.8,
    sog: 0.0,
    cog: 0.0,
    true_heading: null,
    nav_status: 1,
    destination: null,
    is_active: true,
    is_anomaly: true,
    sanctions_match: false,
    dark_fleet_score: 72,
    last_update: NOW,
  },

  // 3. Dark fleet + anomaly — cargo in Baltic Sea
  {
    mmsi: '618723100',
    imo_number: 'IMO9512089',
    vessel_name: 'NORD SPIRIT',
    call_sign: 'TRWK2',
    flag_state: 'Gabon',
    ship_type: 70,
    type_category: 'Cargo',
    type_color: '#EAB308',
    lat: 58.9,
    lon: 17.2,
    sog: 3.1,
    cog: 224.0,
    true_heading: 223,
    nav_status: 0,
    destination: 'KALININGRAD',
    is_active: true,
    is_anomaly: true,
    sanctions_match: false,
    dark_fleet_score: 85,
    last_update: NOW,
  },

  // 4. Sanctions + extreme dark fleet — tanker in Persian Gulf
  {
    mmsi: '511234700',
    imo_number: 'IMO9623017',
    vessel_name: 'AURORA VENTURE',
    call_sign: 'T2BP5',
    flag_state: 'Palau',
    ship_type: 80,
    type_category: 'Tanker',
    type_color: '#EF4444',
    lat: 29.1,
    lon: 48.5,
    sog: 0.0,
    cog: 0.0,
    true_heading: null,
    nav_status: 5,
    destination: 'KHARG ISLAND',
    is_active: true,
    is_anomaly: false,
    sanctions_match: true,
    dark_fleet_score: 91,
    last_update: NOW,
  },

  // 5. Anomaly — cargo in South China Sea
  {
    mmsi: '677412300',
    imo_number: 'IMO9589234',
    vessel_name: 'EASTERN HARMONY',
    call_sign: 'S9BG7',
    flag_state: 'Tanzania',
    ship_type: 70,
    type_category: 'Cargo',
    type_color: '#F97316',
    lat: 22.3,
    lon: 114.2,
    sog: 1.4,
    cog: 311.0,
    true_heading: 310,
    nav_status: 0,
    destination: 'HONG KONG',
    is_active: true,
    is_anomaly: true,
    sanctions_match: false,
    dark_fleet_score: 38,
    last_update: NOW,
  },

  // 6. Dark fleet fishing — near PNG EEZ
  {
    mmsi: '412876300',
    imo_number: null,
    vessel_name: 'HAI FENG 7',
    call_sign: 'BPKJ3',
    flag_state: 'China',
    ship_type: 30,
    type_category: 'Fishing',
    type_color: '#EAB308',
    lat: -8.4,
    lon: 141.2,
    sog: 2.8,
    cog: 76.0,
    true_heading: 75,
    nav_status: 7,
    destination: null,
    is_active: true,
    is_anomaly: false,
    sanctions_match: false,
    dark_fleet_score: 68,
    last_update: NOW,
  },
]
